databases:
  - name: mascote-petshop-db
    databaseName: mascotepetshop
    user: mascote

services:
  - type: web
    name: mascote-petshop
    runtime: docker
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: prod
      - key: DB_HOST
        fromDatabase:
          name: mascote-petshop-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: mascote-petshop-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: mascote-petshop-db
          property: database
      - key: DB_USER
        fromDatabase:
          name: mascote-petshop-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mascote-petshop-db
          property: password
